### ISSUE TITLE
Couldn't connect to default server using localhost or container DNS

### ISSUE THREAD

**Issue by rootxls** [itzg/docker-bungeecord#112]
When I want to connect to my default server using the BungeeCord, it disconnects me and returns the error: "Could not connect to a default or fallback server, please try again later: Server not reachable (timeout). Offline? Incorrectly configured address/port/firewall?" However, my default server is present at the address: localhost:25565. 
I tried to connect both of them with different addresses such as:
- localhost
- 127.0.0.1
- 0.0.0.0
- test-lobby (container name DNS resolved by Docker)
- My public IP

I also tried to modify the server-ip field in server.properties to see if it was not that, I tried:
- 0.0.0.0
- 127.0.0.1

Here is the list of my containers:
![image](https://user-images.githubusercontent.com/45496261/172358704-4a14f6c3-9ab9-4eaa-b0c5-bd67c5298a6d.png)

Proxy logs:
[_test-proxy_logs.txt](https://github.com/itzg/docker-bungeecord/files/8852395/_test-proxy_logs.txt)

Lobby logs:
[_test-lobby_logs.txt](https://github.com/itzg/docker-bungeecord/files/8852410/_test-lobby_logs.txt)

**Comment by itzg** [comment]
Please provide the container configs you are using. Better yet, start back as the baseline examples

https://github.com/itzg/docker-bungeecord/tree/master/docs

and iterate from there.

**Comment by rootxls** [comment]
I changed my BungeeCord config.yml with the one provided in the link you sent, but it doesn't change anything
This is the JSON which i send to DockerEngineAPI (v1.41 / latest) to create the containers:

**Proxy**
```
{
    "Image":"itzg/bungeecord",
    "AutoRemove":true,
    "Env":[
        "TYPE\u003dBUNGEECORD",
        "REPLACE_ENV_VARIABLES\u003dTRUE"
    ],
    "HostConfig":{
        "PortBindings":{
            "25577/tcp":[
                {
                    "HostIp":"0.0.0.0",
                    "HostPort":"25577"
                }
            ]
        },
        "Mounts":[
            {
                "Target":"/config",
                "Source":"C:\\Users\\basti\\Documents\\GitHub\\TestDocker\\src\\main\\resources\\modules\\proxy\\config",
                "Type":"bind",
                "ReadOnly":false
            },
            {
                "Target":"/plugins",
                "Source":"C:\\Users\\basti\\Documents\\GitHub\\TestDocker\\src\\main\\resources\\modules\\proxy\\plugins",
                "Type":"bind",
                "ReadOnly":false
            }
        ],
        "Binds":[
            
        ]
    },
    "Config":{
        "AttachStdin":false,
        "AttachStdout":false,
        "AttachStderr":false
    },
    "Tty":true,
    "OpenStdin":true,
    "Volumes":{
        
    },
    "Args":[
        
    ]
}
```

**Lobby**

```
{
    "Image":"itzg/minecraft-server:java8",
    "AutoRemove":true,
    "Domainname":"test-lobby",
    "Env":[
        "TYPE\u003dCUSTOM",
        "CUSTOM_SERVER\u003d/data/server.jar",
        "EULA\u003dTRUE",
        "REPLACE_ENV_VARIABLES\u003dTRUE",
        "SERVER_PORT\u003d25565",
        "SERVER_NAME\u003dtest-lobby"
    ],
    "HostConfig":{
        "PortBindings":{
            "25565/tcp":[
                {
                    "HostIp":"0.0.0.0",
                    "HostPort":"25565"
                }
            ]
        },
        "Mounts":[
            {
                "Target":"/data",
                "Source":"C:\\Users\\basti\\Documents\\GitHub\\TestDocker\\src\\main\\resources\\modules\\lobby\\data",
                "Type":"bind",
                "ReadOnly":false
            }
        ],
        "Binds":[
            
        ]
    },
    "Config":{
        "AttachStdin":false,
        "AttachStdout":false,
        "AttachStderr":false
    },
    "Tty":true,
    "OpenStdin":true,
    "Volumes":{
        
    },
    "Args":[
        
    ]
}
```

**Comment by itzg** [comment]
I meant the compose file mainly. You have the port bindings flipped for one thing. I would suggest you start with getting it to work with compose and then port that over to using the API directly.

**Comment by rootxls** [comment]
I tried with the compose file, but nothing changes. Do you think my port bindings are reversed? If it's just that problem, I'll try again with a front-end compose to see and then with the API.

**Comment by rootxls** [comment]
Update: I tried changing and inverting the ports on my host to see if they were inverted and they don't seem to be.

**Comment by rootxls** [comment]
Okay so, I did everything you asked, here is the updated configuration for the ports:

![image](https://user-images.githubusercontent.com/45496261/172399708-e8cd2403-4807-4bae-b366-e28850d40a24.png)

Ce qui donne ceci pour le conteneur du proxy:
```json
"PortBindings": {
                "25577/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "25565"
                    }
                ]
            },
```

Here is the configuration of the "mc" server in bungeecord.yml:

```yaml
servers:
  lobby:
    address: test-lobby:25565
    restricted: false
    motd: ""
```

But the issue is still there, it didn't work either with the docker-compose you sent me. I am on WSL with Docker Desktop but it doesn't seem to be a problem but we are never 100% sure

**Comment by rootxls** [comment]
I managed to get it to work with the docker-compose you gave me, however when I change the lobby of the compose to the one I created I can't join. I haven't changed anything in the network configuration, everything is on the bridge.

**Comment by rootxls** [comment]
Update: Now when I associate the lobby of the dialup you gave me, with the proxy I created myself, I don't get exactly the same error:

"disconnected with: Could not connect to a default or fallback server, please try again later:"

But without the misconfigured port/address error.
However, if I try my lobby with the proxy of your compound, I still get this error.

The network level is all on the docker base network.

Translated with www.DeepL.com/Translator (free version)

**Comment by rootxls** [comment]
Update: I managed to get it to work with its own docker compose, but when I do it with the api, it doesn't work. However the parameters are exactly the same, I can provide the JSON data if needed.

Here is the docker-compose used which works:

```
version: '3.9'

services:
  proxy:
    image: itzg/bungeecord
    container_name: test-proxy
    stdin_open: true
    tty: true
    ports:
      - "25577:25577"
    volumes:
      - C:\Users\basti\Documents\GitHub\TestDocker\a remove\lyramc\proxy\config:/config
      - C:\Users\basti\Documents\GitHub\TestDocker\a remove\lyramc\proxy\plugins:/plugins
    environment:
      TYPE: CUSTOM
      BUNGEE_JAR_FILE: "/config/server.jar"

      INIT_MEMORY: 512m
      MAX_MEMORY: 512m

      REPLACE_ENV_VARIABLES: "TRUE"
      ENV_VARIABLE_PREFIX: ""
    restart: "no"
    networks:
      - "backend"
  lobby:
    image: itzg/minecraft-server:java8
    restart: "no"
    tty: true
    stdin_open: true
    container_name: test-lobby
    ports:
      - "25565:25565"
    volumes:
      - C:\Users\basti\Documents\GitHub\TestDocker\a remove\lyramc\lobby:/data
    environment:
      TYPE: "CUSTOM"
      CUSTOM_SERVER: /data/server.jar
      EULA: "TRUE"
      REPLACE_ENV_VARIABLES: "TRUE"
      SERVER_PORT: 25565
      SERVER_NAME: test-lobby
    networks:
      - "backend"

networks:
  backend:
    name: backend
    driver: bridge
    #internal: true # Disable internet
```
