### ISSUE TITLE
`GENERIC_PACK` would be very useful

### ISSUE THREAD

**Issue by ChipWolf** [itzg/docker-bungeecord#113]
`GENERIC_PACK` would be very useful

_Originally posted by @ChipWolf in https://github.com/itzg/docker-bungeecord/issues/96#issuecomment-1157985185_

Similar to the GENERIC_PACK functionality in the minecraft-server container, we'd like to package and ship our proxy configuration in the same manner.
This feature would be kick-ass :)

**Comment by ChipWolf** [comment]
Our current workaround is using an `initContainer` in our Helm release:

```yaml
    initContainers:
      - name: generic-packs
        image: itzg/bungeecord:java17-2022.4.1
        command: ['bash', '-c', 'curl -s https://raw.githubusercontent.com/example-org/gitops-k8s/main/minecraft/generic-packs.sh | bash']
        volumeMounts:
          - name: datadir
            mountPath: /server
        env:
          - name: GENERIC_PACKS_PREFIX
            value: https://cdn.example.org/server/
          - name: GENERIC_PACKS
            value: proxy-base-v1.0.7+en.zip,proxy-includes-v1.1.2.zip
          - name: CFG_MONGODB_GEO
            value: "-emea-headless"
          - name: CFG_SERVER_GEO
            value: emea
          - name: REPLACE_ENV
            value: 'true'
```

`generic-packs.sh`
```bash
#!/bin/bash

set -e -o pipefail

: "${GENERIC_PACKS:=${GENERIC_PACK}}"
: "${GENERIC_PACKS_PREFIX:=}"
: "${GENERIC_PACKS_SUFFIX:=}"

function log() {
  echo "[init] $*"
}

if [[ "${GENERIC_PACKS}" ]]; then
    IFS=',' read -ra packs <<< "${GENERIC_PACKS}"

    packFiles=()
    for packEntry in "${packs[@]}"; do
        pack="${GENERIC_PACKS_PREFIX}${packEntry}${GENERIC_PACKS_SUFFIX}"
        mkdir -p /server/packs
        log "Downloading generic pack from $pack"
        if ! outfile=$(mc-image-helper get -o /server/packs --output-filename --skip-up-to-date "$pack"); then
            log "ERROR: failed to download $pack"
            exit 2
        fi
        packFiles+=("$outfile")
    done

    log "Applying generic pack(s)..."
    original_base_dir=/server/.tmp/generic_pack_base
    base_dir=$original_base_dir
    rm -rf "${base_dir}"
    mkdir -p "${base_dir}"
    for pack in "${packFiles[@]}"; do
    unzip -o -q -d "${base_dir}" "${pack}"
    done

    if [ -f /server/manifest.txt ]; then
    log "Manifest exists from older generic pack, cleaning up ..."
    while read -r f; do
        rm -rf "/server/${f}"
    done < /server/manifest.txt
    find /server -mindepth 1 -depth -type d -empty -delete
    rm -f /server/manifest.txt
    fi

    log "Writing generic pack manifest ... "
    find "${base_dir}" -type f -printf "%P\n" > /server/manifest.txt

    log "Applying generic pack ..."
    cp -R -f "${base_dir}"/* /server
    rm -rf $original_base_dir

    if [[ $REPLACE_ENV ]]; then
      >&2 echo "[info] Interpolating config.yaml with CFG variables..."
      mc-image-helper --debug=true interpolate \
        --replace-env-file-suffixes="conf,yml,toml" \
        --replace-env-prefix="CFG_" \
        "/server"
    fi

    if [ $UID == 0 ]; then
    chown -R bungeecord:bungeecord /server
    fi
else
  log "No generic pack(s) specified"
fi

exit 0
```
