### ISSUE TITLE
Support mounting kubernetes secrets

### ISSUE THREAD

**Issue by alexstaeding** [itzg/docker-bungeecord#129]
I am using the velocity image type which requires a file named `forwarding.secret` in the server root. I tried mounting this file via a Kubernetes secret like this:

```yaml
containers:
  - name: minecraft-proxy
    image: itzg/bungeecord:java17
    ports:
      - containerPort: 25577
    volumeMounts:
      - name: minecraft-proxy-volume
        mountPath: /server/logs
        subPath: logs
      - name: minecraft-proxy-volume
        mountPath: /server/plugins
        subPath: plugins
      - name: minecraft-proxy-volume
        mountPath: /server/velocity.toml
        subPath: velocity.toml
      - name: secret-volume # <--- here
        mountPath: /server/forwarding.secret
        subPath: secret-value
    env:
      - name: TYPE
        value: "VELOCITY"
volumes:
  - name: minecraft-proxy-volume
    persistentVolumeClaim:
      claimName: minecraft-proxy-pvc
  - name: secret-volume
    secret:
      secretName: minecraft-proxy-secret
```

...but the container hangs with this output:

```
Defaulted container "minecraft-proxy" out of: minecraft-proxy, init-velocity (init)
[init] Resolving type given VELOCITY
[init] Downloading https://papermc.io/api/v2/projects/velocity/versions/3.2.0-SNAPSHOT/builds/260/downloads/velocity-3.2.0-SNAPSHOT-260.jar
[mc-image-helper] 19:00:36.213 INFO  : Downloaded /server/velocity-3.2.0-SNAPSHOT-260.jar
chown: changing ownership of '/server/forwarding.secret': Read-only file system
```

If I instead mount `/server/forwarding.secret` via the minecraft-proxy-volume, the server starts without a problem.
