### ISSUE TITLE
query port not exposed (udp)

### ISSUE THREAD

**Issue by quiquelhappy** [itzg/docker-bungeecord#131]
Hello,
I haven't done any testing regarding this, but it seems like the query port is not exposed on the dockerfile, hence, the player list is unavailable.

I've set ``query_enabled: true`` with ``- query_port: 25577`` on the bungee ``config.yml``, and I made sure to map the port:
```yml
  proxy:
    user: "${uid}:${gid}"
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: itzg/bungeecord
    container_name: "${proxy}"
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - ./proxy:/server:rw
    ports:
      - "25565:25577/tcp"
      - "25565:25577/udp"
    environment:
      TYPE: "BUNGEECORD"
      BUNGEE_JOB_ID: "lastStableBuild"
      MEMORY: "512m"
      ENABLE_RCON: false
```
This may be user error, or a plugin making my life difficult, but for what I've seen, it looks like only ``EXPOSE $SERVER_PORT`` is exported, but it should be exposing the UDP port too with ``EXPOSE $SERVER_PORT/udp`` as seen [here](https://stackoverflow.com/a/27596415).
