### ISSUE TITLE
[Server thread/ERROR]: Failed to validate profile key: Invalid signature for profile public key.

### ISSUE THREAD

**Issue by Zorua162** [itzg/docker-bungeecord#143]
When I use the Bungeecord config as given by the docs I get the error `[Server thread/ERROR]: Failed to validate profile key: Invalid signature for profile public key.`

In game this shows as "Invalid signature for profile public key. Try restarting your game". I have tried restarting my game, and this hasn't worked. (I've been having this issue for the past two weeks and have tried multiple times including fill pc restarts).

I've tried messing with some of the settings (including removing BUNGEE_JAR_REVISION: "1"), but I get the same error. I've also tried making the /server mount to a local folder as a volume, but this also didn't work

## Settings
After all this my `docker-compose.yml` file ended up looking like this:
```version: '3.5'

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
  bungeecord:
    image: itzg/bungeecord
    environment:
      CFG_MOTD: Powered by Docker
      REPLACE_ENV_VARIABLES: "true"
    ports:
      - "25565:25577"
    volumes:
      - ./config.yml:/config/config.yml
      - ./bungeecord:/server
```

and my config.yml looks like this:
```
server_connect_timeout: 5000
listeners:
- motd: ${CFG_MOTD}
  priorities:
  - lobby
  host: 0.0.0.0:25577
  max_players: 1
  force_default_server: false
  tab_size: 60
  forced_hosts:
    pvp.md-5.net: pvp
  tab_list: GLOBAL_PING
  bind_local_address: true
  ping_passthrough: false
  query_enabled: false
  query_port: 25577
  proxy_protocol: false
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 3
prevent_proxy_connections: false
timeout: 30000
player_limit: -1
ip_forward: false
groups:
  md_5:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: 19659f49-ed6b-47e3-8b81-63bd14ade63a
online_mode: true
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  lobby:
    address: mc:25565
    restricted: false
    motd: ${CFG_MOTD}
```

## Logs
Using the above settings:
mc_1 logs: https://pastebin.com/3cjP0sDC
bungeecord_1 logs: https://pastebin.com/zFPasAfw

I have also tried just running the Minecraft server container on its own, and I can connect to that fine. 

As my backend I am using Podman version 4.6.2 and podman-compose. I have tried with Docker and had the same error. I am also on WSL with the experimental networking settings enabled. I've tried to reproduce the bug on my VPS, however I struggled with further network issues there which I assume are my own fault, but as I am quite new to containers I was unable to diagnose those there to be able to reproduce this.

I have also tried setting the enforce-secure-profile setting to false in the server.properties, but I wasn't able to get this to work, and ideally I would rather get a fix for the root cause of the problem instead of adding a work around, however if needed I will go with this.

Edit: Tried to fix formatting of the config files
