### ISSUE TITLE
When specifying modrinth plugins on velocity the logs output that plugins are downlaoding but no plugins get loaded

### ISSUE THREAD

**Issue by Player505** [itzg/docker-bungeecord#163]
**Compose File**
```
version: "3.8"

services:
  proxy:
    image: itzg/bungeecord
    tty: true
    stdin_open: true
    ports:
      - "25565:25577"
      - "19132:19132/udp"
      - "24454:24454/udp"
    volumes:
     - ./velocity.toml:/server/velocity.toml
     - ./forwarding.secret:/server/forwarding.secret
    environment:
      TYPE: VELOCITY
     #ICON: ~/server-icon.png
      MEMORY: 512m
      MODRINTH_PROJECTS: viaversion, viabackwards, viarewind
      MINECRAFT_VERSION: "1.20.1"
    restart: always
```

**Output log**
```
proxy-1  | [init] Resolving type given VELOCITY
proxy-1  | [mc-image-helper] 12:17:20.023 INFO  : Downloaded /server/velocity-3.3.0-SNAPSHOT-346.jar
proxy-1  | [mc-image-helper] 12:17:25.982 INFO  : Downloading ViaBackwards-4.9.1.jar
proxy-1  | [mc-image-helper] 12:17:27.434 INFO  : Downloading ViaVersion-4.9.2.jar
proxy-1  | [mc-image-helper] 12:17:28.706 INFO  : Downloading ViaRewind-3.0.5.jar
proxy-1  | [init] Setting initial memory to 512m and max to 512m
proxy-1  | [12:17:32 INFO]: Booting up Velocity 3.3.0-SNAPSHOT (git-59567512-b346)...
proxy-1  | [12:17:32 INFO]: Loading localizations...
proxy-1  | [12:17:33 INFO]: Connections will use epoll channels, libdeflate (Linux x86_64) compression, OpenSSL1.1.x (Linux x86_64) ciphers
proxy-1  | [12:17:33 INFO]: Loading plugins...
proxy-1  | [12:17:33 INFO]: Loaded 0 plugins
proxy-1  | [12:17:33 INFO]: Listening on /0.0.0.0:25577
proxy-1  | [12:17:33 INFO]: Velocity and some of its plugins collect metrics and send them to bStats (https://bStats.org).
proxy-1  | [12:17:33 INFO]: bStats collects some basic information for plugin authors, like how many people use
proxy-1  | [12:17:33 INFO]: their plugin and their total player count. It's recommended to keep bStats enabled, but
proxy-1  | [12:17:33 INFO]: if you're not comfortable with this, you can opt-out by editing the config.txt filein
proxy-1  | [12:17:33 INFO]: the '/plugins/bStats/' folder and setting enabled to false.
proxy-1  | [12:17:33 INFO]: Done (2.35s)!
```

Also when I go into the container the plugins folder is empty
