### ISSUE TITLE
Could not connect to default server with docker compose

### ISSUE THREAD

**Issue by ColinTree** [itzg/docker-bungeecord#21]
I had checked #13 but my situation is a bit different from that case.

I tried to use docker compose so that I can do quick start-ups. Before that I was using docker compose for servers exposing port to the machine network and start bungee manually without docker, and everything works. After moving bungee into docker compose, user start to fail connecting to servers via bungee.

I noticed that the address in `config.yml` should different from `localhost:port` when bungee is in docker environment.
![image](https://user-images.githubusercontent.com/22613139/80627019-a23d3500-8a92-11ea-9f57-9f045e0018de.png)
And I did make a change to that but it still not works.

Since docker compose would give containers a generated name rather than container name in `docker-compose.yml`. For example, my compose config is in `/mc/pc` and the content is pasted below. 

```yml
version: '3.7'

services:
  lobby:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MAX_MEMORY: "4G"
      VERSION: "1.15.2"
      USE_AIKAR_FLAGS: "TRUE"
    volumes:
      - /mc/pc/lobby:/data
    command: --noconsole
    restart: always

  bungee:
    image: itzg/bungeecord
    ports:
      - 25565:25577
    volumes:
      - /mc/pc/bungee/server:/server
    restart: always
    links:
      - lobby
```

![image](https://user-images.githubusercontent.com/22613139/80627696-a61d8700-8a93-11ea-96fb-6247497dff0f.png)
The lobby container is now named `pc_lobby_1` but not `lobby`.

So I tried both

```yml
servers:
  lobby:
    motd: ...
    address: lobby:20000
    restricted: false
```

and

```yml
servers:
  lobby:
    motd: ...
    address: pc_lobby_1:20000
    restricted: false
```

The first config show a same error when attempt to connect server locally, and the second one crashes the bungee server directly:

![image](https://user-images.githubusercontent.com/22613139/80628300-7e7aee80-8a94-11ea-922a-24f7e4d47a23.png)

I'm not sure if I had provided enough message, if any other config file is required to trace the issue I could paste them below.

Thanks in advanced!

**Comment by iverly** [comment]
Hey,

Firstly, if you need to see what is the hostname. You can `cat /etc/hosts` in the container. But, with docker-compose, the host of your others containers is the name of the service. In your case is `lobby`

Secondly, you don't need to link your lobby with your lobby because docker-compose create a network for you. 

And why did you use `20000` as port ? The target port of itzg/docker-minecraft-server is 25565 (https://github.com/itzg/docker-minecraft-server/blob/master/Dockerfile#L27)
**If you have changed your port of your Minecraft-server, set it back to 25565 !**

With these modifications, your `docker-compose.yml` look like this:

```
version: '3.7'

services:
  lobby:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MAX_MEMORY: "4G"
      VERSION: "1.15.2"
      USE_AIKAR_FLAGS: "TRUE"
    volumes:
      - /mc/pc/lobby:/data
    command: --noconsole
    restart: always

  bungee:
    image: itzg/bungeecord
    ports:
      - 25565:25577
    volumes:
      - /mc/pc/bungee/server:/server
    restart: always
```

And your `bungee.yml`:

```
servers:
  lobby:
    motd: ...
    address: lobby:25565
    restricted: false
```

**Comment by itzg** [comment]
To add some background to @iverly 's great feedback, this is the docs that describes the networking feature in docker-compose, which are very cool:

https://docs.docker.com/compose/networking/

**Comment by C0Nd3Mnd** [comment]
I would like to add to this:

My Bungeecord config:

```yaml
# ...
servers:
  lobby:
    motd: test - lobby
    address: minecraft_lobby:25565
    restricted: false
```

The `docker-compose.yml` for Bungeecord:

```yaml
version: '3'
services:
  bungeecord:
    image: itzg/bungeecord
    container_name: bungeecord
    restart: always
    ports:
      - '25565:25577'
    volumes:
      - ./server:/server
```

The `docker-compose.yml` of a Spigot server (`minecraft_lobby`):

```yaml
version: '3'
services:
  minecraft_lobby:
    image: itzg/minecraft-server
    container_name: minecraft_lobby
    restart: always
    environment:
      TYPE: SPIGOT
      EULA: 'TRUE'
      MEMORY: 2G
      USE_AIKAR_FLAGS: 'true'
      VERSION: '1.15.2'
      ONLINE_MODE: 'FALSE'
    networks:
      - bungeecord_default
      - default
    volumes:
      - ./data:/data
networks:
  bungeecord_default:
    external: true
```

And I get the same error as @ColinTree:

```
09:33:08 [SEVERE] Exception in thread "main"
09:33:08 [SEVERE] java.lang.IllegalArgumentException: Invalid host/address: minecraft_lobby:25565
09:33:08 [SEVERE]     at net.md_5.bungee.Util.getAddr(Util.java:54)
09:33:08 [SEVERE]     at net.md_5.bungee.conf.YamlConfig.getServers(YamlConfig.java:221)
09:33:08 [SEVERE]     at net.md_5.bungee.conf.Configuration.load(Configuration.java:106)
09:33:08 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:273)
09:33:08 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
09:33:08 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```

I can resolve the hostname within a shell (i.e. `bash`) inside the Bungeecord container:

```
bash-4.4# nslookup minecraft_lobby
nslookup: can't resolve '(null)': Name does not resolve

Name:      minecraft_lobby
Address 1: 172.18.0.3 minecraft_lobby.bungeecord_default
```

I tried using `minecraft_lobby.bungeecord_default` as well, but it wouldn't work.

It works when I use the IP address of the `minecraft_lobby` server instead of the hostname, like so:

```yaml
# ...
servers:
  lobby:
    motd: test - lobby
    address: 172.18.0.3:25565
    restricted: false
```

But that's not a good solution at all, since the IP address could change (container restarts, different setup etc.).

It seems that Bungeecord/Java doesn't resolve internal hostnames properly. Any way to fix this/work around it?
