### ISSUE TITLE
Support for environment variable passthrough

### ISSUE THREAD

**Issue by hfoxy** [itzg/docker-bungeecord#32]
Hi,

I'm currently using itzg/minecraft-server to host my MC servers, which has the ability to passthrough environment variables like so:
```
minecraft:
  image: itzg/minecraft-server
  restart: always
  environment:
    EULA: "true"
    ONLINE_MODE: "false"
    TYPE: PAPER
    VERSION: 1.16.1
    MEMORY: 6G
    VAULT_TOKEN: ~
    MONGO_VAULT_CREDENTIAL: ~
    REDIS_VAULT_CREDENTIAL: ~
    MAX_PLAYERS: 200
    ALLOW_NETHER: "false"
    GENERATE_STRUCTURES: "false"
    USE_AIKAR_FLAGS: "true"
  volumes:
    - /data/minecraft/plugins:/plugins
  networks:
    - myNetwork
  deploy:
    mode: replicated
    replicas: 1
```

Note that, `VAULT_TOKEN`, `MONGO_VAULT_CREDENTIAL` and `REDIS_VAULT_CREDENTIAL` are all set on the Minecraft server.

When doing the same using itzg/bungeecord, the environment variables are not passed through to the app, like this:
```
bungeecord:
  image: itzg/bungeecord
  restart: always
  ports:
    - "25565:25577"
  environment:
    TYPE: WATERFALL
    MEMORY: 2G
    VAULT_TOKEN: ~
    MONGO_VAULT_CREDENTIAL: ~
    REDIS_VAULT_CREDENTIAL: ~
  volumes:
    - /data/bungeecord/plugins:/plugins
    - /data/bungeecord/config:/config
    - /data/bungeecord/server:/server
  networks:
    - myNetwork
  deploy:
    mode: replicated
    replicas: 1
```

The same environment variables are not set, or at the very least, they are not visible in `System#getenv()` and are null in `System#getenv(String)`

Is this intentional/something Bungee related? I've looked through the Dockerfile and haven't spotted anything that sticks out in terms of scraping the environment variables out, nor is there any documentation of a prefix that is required to pass through.
