### ISSUE TITLE
Unable to setup proxy using own jar 

### ISSUE THREAD

**Issue by CDFN** [itzg/docker-bungeecord#34]
Hi, I'm trying to setup my proxy using custom jar. Currently I'm getting error:
```
proxy_1  | Resolving type given CUSTOM
proxy_1  | Using custom server jar at proxy.jar ...
proxy_1  | Downloading proxy.jar
proxy_1  | curl: (6) Could not resolve host: proxy.jar
proxy_1  | ERROR: failed to download
```

with docker-compose.yml:
```
  proxy:
    stdin_open: true
    tty: true
    image: itzg/bungeecord
    ports:
      - '25565:25565'
    volumes:
      - './bungee-vol:/server'
    environment:
      TYPE: "CUSTOM"
      BUNGEE_JAR_URL: "proxy.jar"
      MEMORY: "2G"
```

With [minecraft-server](https://github.com/itzg/docker-minecraft-server) custom jar works perfectly fine.
