### ISSUE TITLE
Reconnecting does not work when server restarts

### ISSUE THREAD

**Issue by alvarlagerlof** [itzg/docker-bungeecord#80]
I've noticed that when a container using [docker-minecraft-server](https://github.com/itzg/docker-minecraft-server) restarts, I can no longer connect to it using `/server x` even though it is up and running. First boots work, and restarting the bungeecord container works too.

![image](https://user-images.githubusercontent.com/14835120/143135638-07bf53f5-18d8-4a8d-b957-4e66ba420384.png)

My config looks like this.
```yml
servers:
  survival:
    address: survival:25565
    restricted: false
  minigames:
    address: minigames:25565
    restricted: false
  flat:
    address: flat:25565
    restricted: false
```
